"""Django settings for untitled project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = (
    Path(__file__).resolve().parent.parent
)  # * setting base dir as root folder for project
sys.path.insert(
    0,
    os.path.join(BASE_DIR, "apps"),  # noqa: PTH118
)  # * setting apps folder as root folder for apps
