# Generated by Django 5.0.1 on 2024-01-23 14:23

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_resetpasswordtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    1,
                    23,
                    14,
                    53,
                    30,
                    667728,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.CreateModel(
            name="UserDeletionRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "delete_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2024,
                            2,
                            22,
                            14,
                            23,
                            30,
                            668552,
                            tzinfo=datetime.timezone.utc,
                        ),
                        null=True,
                        verbose_name="delete date",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user deletion requests",
                "verbose_name_plural": "user deletion requests",
                "abstract": False,
            },
        ),
    ]
