# Generated by Django 5.0.1 on 2024-01-23 14:46

import datetime
import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_resetpasswordtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 23, 15, 16, 36, 322493, tzinfo=datetime.timezone.utc
                ),
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="userdeletionrequests",
            name="delete_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 22, 14, 46, 36, 323250, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="delete date",
            ),
        ),
        migrations.AlterField(
            model_name="userdeletionrequests",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deletion_request",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.CreateModel(
            name="UserRecoveryToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        max_length=255,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
