# Generated by Django 5.0.1 on 2024-01-23 15:10

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_resetpasswordtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecoverytoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resetpasswordtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    1,
                    23,
                    15,
                    40,
                    38,
                    213828,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="userdeletionrequests",
            name="delete_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024,
                    2,
                    22,
                    15,
                    10,
                    38,
                    216656,
                    tzinfo=datetime.timezone.utc,
                ),
                null=True,
                verbose_name="delete date",
            ),
        ),
    ]
