# Generated by Django 5.0.1 on 2024-01-24 12:07

import datetime
import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_userrecoverytoken_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertokenemailvalidation",
            name="user",
        ),
        migrations.AlterField(
            model_name="resetpasswordtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    1,
                    24,
                    12,
                    37,
                    7,
                    711389,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="expires at",
            ),
        ),
        migrations.CreateModel(
            name="UserEmailValidationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        max_length=255,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="validated at",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            1,
                            24,
                            12,
                            37,
                            7,
                            710972,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="expires at",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_email_validation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user token email validation",
                "verbose_name_plural": "user token email validations",
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="UserDeletionRequests",
        ),
        migrations.DeleteModel(
            name="UserTokenEmailValidation",
        ),
    ]
