# Generated by Django 5.0.1 on 2024-01-24 14:00

import datetime
import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_usertokenemailvalidation_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useremailvalidationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    1,
                    24,
                    14,
                    30,
                    11,
                    206797,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="expires at",
            ),
        ),
        migrations.CreateModel(
            name="UserResetPasswordToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        max_length=255,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            1,
                            24,
                            14,
                            30,
                            11,
                            207213,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="expires at",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "reset password token",
                "verbose_name_plural": "reset password tokens",
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ResetPasswordToken",
        ),
    ]
