# Generated by Django 5.0.1 on 2024-01-27 06:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_useremailvalidationtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 3, 6, 31, 8, 680806, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_token_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=255, verbose_name="username"),
        ),
        migrations.AlterField(
            model_name="useremailvalidationtoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 3, 11, 8, 28, 679595, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="userresetpasswordtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 3, 6, 48, 28, 680067, tzinfo=datetime.timezone.utc
                ),
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="userresetpasswordtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reset_password_token_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
