version: "latest"

services:
  untitled: # ! 👈 name of the service
    build: . # path to the Dockerfile
    container_name: untitled-dev # ! 👈 name of the container
    restart: always # restart the container if it stops
    volumes: # mount the current directory to the container
      - ..:/workspace:cached # mount the current directory as workspace to the container
    environment: # set environment variables
      POETRY_VIRTUALENVS_IN_PROJECT: True
      ENVIRONMENT: "development"
      # ___ Base settings ___
      DEBUG: True
      # SECRET_KEY: ""
      # ___ Admin ___
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: password
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_FIRST_NAME: Admin
      DJANGO_SUPERUSER_LAST_NAME: ADMIN
      # ___ Database ___
      # DB_ENGINE: django.db.backends.postgresql
      # DB_NAME: postgres
      # DB_USER: postgres
      # DB_PASSWORD: postgres
      # DB_HOST: db
      # DB_PORT: 5432
      # ___ Static files ___
      STATIC_URL: /static/
      STATIC_ROOT: /staticfiles/
      # ___ Globalization ___
      LANGUAGE_CODE: en-us
      TIME_ZONE: UTC

    command: /bin/sh -c "while sleep 1000; do :; done" # * keep the container running
